//Global types
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const F4_FETCH_COUNTRY_LIST = 'F4_FETCH_COUNTRY_LIST';
export const F4_CLEAR_COUNTRY_LIST = 'F4_CLEAR_COUNTRY_LIST';
export const F4_GET_REGION_LIST = 'F4_GET_REGION_LIST';
export const F4_CLEAR_REGION_LIST = 'F4_CLEAR_REGION_LIST';
export const F4_GET_CITIES_LIST = 'F4_GET_CITIES_LIST';
export const F4_CLEAR_CITIES_LIST = 'F4_CLEAR_CITIES_LIST';
export const F4_GET_CEMETRY_LIST = 'F4_GET_CEMETRY_LIST';
export const F4_CLEAR_CEMETRY_LIST = 'F4_CLEAR_CEMETRY_LIST';
export const LOADING = 'LOADING';

//personels
export const USERS_ALL = 'USERS_ALL';
export const SAVE_USER = 'SAVE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SAVE_ERROR = 'SAVE_ERROR';
export const USERS_ERROR = 'USERS_ERROR';
export const CLEAR_DYNOBJ_USERS = 'CLEAR_DYNOBJ_USERS';
export const CHANGE_LANG = 'CHANGE_LANG';
export const USER_MODAL_DELETE = 'USER_MODAL_DELETE';
export const ADD_MODAL_OPEN = 'ADD_MODAL_OPEN';
export const USER_MODAL_UPDATE = 'USER_MODAL_UPDATE';
export const DELETE_USER = 'DELETE_USER';
export const VARIFY_OK = 'VARIFY_OK';

//dashboard
export const TOMB_SERVICES = 'TOMB_SERVICES';
export const TOMB_SERVICES_MODAL = 'TOMB_SERVICES_MODAL';
